// Copyright (c) MicroElements. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using MicroElements.AspNetCore.OpenApi.FluentValidation.AspNetCore;
using MicroElements.AspNetCore.OpenApi.FluentValidation.Generation;
using MicroElements.OpenApi.FluentValidation;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Options;
#if !OPENAPI_V2
using Microsoft.OpenApi.Models;
#endif

namespace MicroElements.AspNetCore.OpenApi.FluentValidation
{
    /// <summary>
    /// ServiceCollection extensions for Microsoft.AspNetCore.OpenApi integration.
    /// </summary>
    [SuppressMessage("ReSharper", "RedundantTypeArgumentsOfMethod", Justification = "More obvious")]
    public static class ServiceCollectionExtensions
    {
        /// <summary>
        /// Adds FluentValidation rules to OpenAPI documents generated by Microsoft.AspNetCore.OpenApi.
        /// </summary>
        /// <param name="services">Services.</param>
        /// <param name="configure">Optional configure action for <see cref="SchemaGenerationOptions"/>.</param>
        /// <returns>The same service collection.</returns>
        public static IServiceCollection AddFluentValidationRulesToOpenApi(
            this IServiceCollection services,
            Action<SchemaGenerationOptions>? configure = null)
        {
            // Register the schema transformer for DI activation.
            // Transient (not Scoped) because .NET 10 build-time document generation
            // runs without an HTTP scope, causing scoped resolution to fail.
            services.TryAddTransient<FluentValidationSchemaTransformer>();

            // Register JsonSerializerOptions (reference to Microsoft.AspNetCore.Mvc.JsonOptions.Value)
            services.TryAddTransient<AspNetJsonSerializerOptions>(provider => new AspNetJsonSerializerOptions(provider.GetJsonSerializerOptionsOrDefault()));

            // TryAdd ensures we only register a bare JsonSerializerOptions fallback when the host
            // hasn't already registered one (e.g. via AddControllers or AddJsonOptions).
            // This keeps the library non-intrusive while still providing a default for minimal APIs.
            services.TryAddTransient<JsonSerializerOptions>(provider => provider.GetService<AspNetJsonSerializerOptions>()?.Value!);

            // Adds name resolver. For example when property name in schema differs from property name in dotnet class.
            services.TryAddSingleton<INameResolver, SystemTextJsonNameResolver>();

            // Adds default IValidatorRegistry.
            // Transient for the same reason as FluentValidationSchemaTransformer above.
            services.TryAddTransient<IValidatorRegistry, ServiceProviderValidatorRegistry>();

            // Issue #165: Register IServiceCollection for keyed validator discovery at resolution time
            services.TryAddSingleton<IServiceCollection>(services);

            // Adds IFluentValidationRuleProvider
            services.TryAddSingleton<IFluentValidationRuleProvider<OpenApiSchema>, DefaultFluentValidationRuleProvider>();

            // DI injected services
            services.TryAddTransient<IServicesContext, ServicesContext>();

            // Schema generation configuration
            if (configure != null)
                services.Configure<SchemaGenerationOptions>(configure);

            // PostConfigure SchemaGenerationOptions
            services.TryAddEnumerable(
                ServiceDescriptor.Transient<IPostConfigureOptions<SchemaGenerationOptions>, MicroElements.OpenApi.AspNetCore.FillDefaultValuesPostConfigureOptions>());

            return services;
        }
    }
}
