// Copyright (c) MicroElements. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using FluentValidation;
using MicroElements.OpenApi;
using MicroElements.OpenApi.Core;
using MicroElements.OpenApi.FluentValidation;
using MicroElements.OpenApi.FluentValidation.FileUpload;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
#if OPENAPI_V2
using Microsoft.OpenApi;
#else
using Microsoft.OpenApi.Models;
#endif

namespace MicroElements.AspNetCore.OpenApi.FluentValidation
{
    /// <summary>
    /// <see cref="IOpenApiOperationTransformer"/> that applies FluentValidation rules
    /// to query, route, and header parameters generated by Microsoft.AspNetCore.OpenApi.
    /// Issue #200: Query parameters with [AsParameters] were not getting validation constraints.
    /// </summary>
    public class FluentValidationOperationTransformer : IOpenApiOperationTransformer
    {
        private readonly ILogger _logger;
        private readonly IValidatorRegistry _validatorRegistry;
        private readonly IReadOnlyList<IFluentValidationRule<OpenApiSchema>> _rules;
        private readonly SchemaGenerationOptions _schemaGenerationOptions;

        /// <summary>
        /// Initializes a new instance of the <see cref="FluentValidationOperationTransformer"/> class.
        /// </summary>
        public FluentValidationOperationTransformer(
            ILoggerFactory? loggerFactory = null,
            IValidatorRegistry? validatorRegistry = null,
            IFluentValidationRuleProvider<OpenApiSchema>? fluentValidationRuleProvider = null,
            IEnumerable<FluentValidationRule>? rules = null,
            IOptions<SchemaGenerationOptions>? schemaGenerationOptions = null)
        {
            _logger = loggerFactory?.CreateLogger(typeof(FluentValidationOperationTransformer)) ?? NullLogger.Instance;
            _validatorRegistry = validatorRegistry ?? throw new ArgumentNullException(nameof(validatorRegistry));

            fluentValidationRuleProvider ??= new DefaultFluentValidationRuleProvider(schemaGenerationOptions);
            _rules = fluentValidationRuleProvider.GetRules().ToArray().OverrideRules(rules);
            _schemaGenerationOptions = schemaGenerationOptions?.Value ?? new SchemaGenerationOptions();

            _logger.LogDebug("FluentValidationOperationTransformer Created");
        }

        /// <inheritdoc />
        public Task TransformAsync(
            OpenApiOperation operation,
            OpenApiOperationTransformerContext context,
            CancellationToken cancellationToken)
        {
            try
            {
                if (operation.Parameters != null && operation.Parameters.Count > 0)
                {
                    ApplyRulesToParameters(operation, context);
                }

                // Issue #216: emit multipart/form-data encoding.contentType for IFormFile parts.
                ApplyRulesToRequestBody(operation, context);
            }
            catch (Exception e)
            {
                _logger.LogWarning(0, e, "Error applying FluentValidation rules to operation parameters");
            }

            return Task.CompletedTask;
        }

        /// <summary>
        /// Issue #216: writes <c>encoding.&lt;part&gt;.contentType</c> for IFormFile parts restricted via
        /// <c>.FileContentType(...)</c>. The part key is taken verbatim from the multipart schema and matched to the
        /// rule name-insensitively, so it works whether the part schema is inline (net9) or a <c>$ref</c> (net10) —
        /// only the property key is needed, never the resolved part schema.
        /// </summary>
        private void ApplyRulesToRequestBody(OpenApiOperation operation, OpenApiOperationTransformerContext context)
        {
#if OPENAPI_V2
            var requestBody = operation.RequestBody as OpenApiRequestBody;
#else
            var requestBody = operation.RequestBody;
#endif
            if (requestBody?.Content == null)
                return;

            if (!requestBody.Content.TryGetValue("multipart/form-data", out var mediaType) || mediaType == null)
                return;

            var partKeys = GetFormPartKeys(mediaType.Schema, context);
            if (partKeys.Count == 0)
                return;

            var methodInfo = GetMethodInfo(context.Description);
            if (methodInfo == null)
                return;

            foreach (var parameter in methodInfo.GetParameters())
            {
                var validator = _validatorRegistry.GetValidator(parameter.ParameterType);
                if (validator == null)
                    continue;

                var contentTypeRules = FileUploadIntrospection
                    .GetFileContentTypeValidators(validator, parameter.ParameterType, _schemaGenerationOptions)
                    .ToList();
                if (contentTypeRules.Count == 0)
                    continue;

                foreach (var partKey in partKeys)
                {
                    var allowed = contentTypeRules
                        .Where(rule => rule.MemberName.EqualsIgnoreAll(partKey))
                        .Select(rule => rule.Meta.AllowedContentTypes)
                        .FirstOrDefault();
                    if (allowed == null || allowed.Count == 0)
                        continue;

                    mediaType.Encoding ??= new Dictionary<string, OpenApiEncoding>();
                    mediaType.Encoding[partKey] = new OpenApiEncoding { ContentType = string.Join(", ", allowed) };
                }
            }
        }

        /// <summary>
        /// Resolves the multipart form part names. The form schema is inline on net9 (and for some net10 endpoints),
        /// but on net10 the whole body is often a <c>$ref</c> to a component whose <c>Target</c> is not yet resolved
        /// when the operation transformer runs — so resolve that component from the document's registered schemas.
        /// </summary>
        private static IReadOnlyCollection<string> GetFormPartKeys(
#if OPENAPI_V2
            IOpenApiSchema? schema,
#else
            OpenApiSchema? schema,
#endif
            OpenApiOperationTransformerContext context)
        {
            if (schema?.Properties is { Count: > 0 })
                return schema.Properties.Keys.ToList();

#if OPENAPI_V2
            if (schema is OpenApiSchemaReference schemaRef
                && schemaRef.Reference?.Id is { } refId
                && context.Document?.Components?.Schemas is { } componentSchemas
                && componentSchemas.TryGetValue(refId, out var component)
                && component.Properties is { Count: > 0 })
            {
                return component.Properties.Keys.ToList();
            }
#endif

            return Array.Empty<string>();
        }

        private void ApplyRulesToParameters(OpenApiOperation operation, OpenApiOperationTransformerContext context)
        {
            var methodInfo = GetMethodInfo(context.Description);

            // Group parameters by container type to avoid redundant validator lookups and schema builds.
            var parameterGroups = new Dictionary<Type, (IValidator Validator, OpenApiSchema Schema)>();

            foreach (var operationParameter in operation.Parameters)
            {
                var apiParameterDescription = context.Description.ParameterDescriptions
                    .FirstOrDefault(d => d.Name.Equals(operationParameter.Name, StringComparison.InvariantCultureIgnoreCase));

                var modelMetadata = apiParameterDescription?.ModelMetadata;
                if (modelMetadata == null)
                    continue;

                // Fallback: resolve container type from [AsParameters] attribute
                var parameterType = modelMetadata.ContainerType
                    ?? ResolveContainerType(operationParameter.Name, methodInfo);

                if (parameterType == null)
                    continue;

                // Reuse validator and schema for the same container type
                if (!parameterGroups.TryGetValue(parameterType, out var cached))
                {
                    var validator = _validatorRegistry.GetValidator(parameterType);
                    if (validator == null)
                        continue;

                    var schema = BuildSchemaForType(parameterType);
                    if (schema.Properties == null || schema.Properties.Count == 0)
                        continue;

                    cached = (validator, schema);
                    parameterGroups[parameterType] = cached;
                }

                // Issue #211: For a flattened nested [FromQuery] parameter (e.g. "RequiredSubType.SubProperty")
                // only reflect the nested type's validation when it is actually reachable from the ROOT validator
                // via SetValidator/ChildRules. FluentValidation never auto-validates a child object from DI, so an
                // unwired nested validator would document constraints that runtime validation never enforces.
                if (operationParameter.Name.IndexOf('.') >= 0
                    && !IsNestedValidationReachable(operationParameter.Name, methodInfo))
                {
                    continue;
                }

                // Issue #209: a flattened nested parameter may be marked required only when EVERY ancestor
                // segment of the dot-path is itself required.
                var pathRequired = IsParameterPathRequired(operationParameter.Name, methodInfo);

                ApplyRulesToParameter(operationParameter, parameterType, cached.Validator, cached.Schema, pathRequired);
            }
        }

        private void ApplyRulesToParameter(
#if OPENAPI_V2
            IOpenApiParameter operationParameter,
#else
            OpenApiParameter operationParameter,
#endif
            Type parameterType,
            IValidator validator,
            OpenApiSchema schema,
            bool pathRequired)
        {
            var schemaPropertyName = operationParameter.Name;

            // For nested [FromQuery] parameters (e.g., "operation.op"), use only the leaf name
            var dotIndex = schemaPropertyName.LastIndexOf('.');
            if (dotIndex >= 0)
                schemaPropertyName = schemaPropertyName.Substring(dotIndex + 1);

            // Find matching property in schema
            var apiProperty = OpenApiSchemaCompatibility.GetProperties(schema)
                .FirstOrDefault(property => property.Key.EqualsIgnoreAll(schemaPropertyName));
            if (apiProperty.Key != null)
            {
                schemaPropertyName = apiProperty.Key;
            }
            else
            {
                var propertyInfo = parameterType.GetProperty(schemaPropertyName);
                if (propertyInfo != null && _schemaGenerationOptions.NameResolver != null)
                {
                    schemaPropertyName = _schemaGenerationOptions.NameResolver.GetPropertyName(propertyInfo);
                }
            }

            var schemaProvider = new AspNetCoreSchemaProvider(null, _logger);
            var schemaContext = new AspNetCoreSchemaGenerationContext(
                schema: schema,
                schemaType: parameterType,
                rules: _rules,
                schemaGenerationOptions: _schemaGenerationOptions,
                schemaProvider: schemaProvider);

            FluentValidationSchemaBuilder.ApplyRulesToSchema(
                schemaType: parameterType,
                schemaPropertyNames: new[] { schemaPropertyName },
                validator: validator,
                logger: _logger,
                schemaGenerationContext: schemaContext);

            // Copy required flag (Issue #209: only when the whole dot-path is required)
            if (pathRequired && OpenApiSchemaCompatibility.RequiredContains(schema, schemaPropertyName))
            {
#if OPENAPI_V2
                if (operationParameter is OpenApiParameter openApiParameter)
                    openApiParameter.Required = true;
#else
                operationParameter.Required = true;
#endif
            }

            // Copy validation constraints from schema property to parameter schema
#if OPENAPI_V2
            var parameterSchema = operationParameter.Schema as OpenApiSchema;
#else
            var parameterSchema = operationParameter.Schema;
#endif
            if (parameterSchema != null)
            {
                if (OpenApiSchemaCompatibility.TryGetProperty(schema, schemaPropertyName, out var property))
                {
                    if (property != null)
                    {
                        CopyValidationProperties(property, parameterSchema);
                    }
                }
            }
        }

        /// <summary>
        /// Builds a temporary OpenApiSchema for a type by reflecting its properties.
        /// </summary>
        private OpenApiSchema BuildSchemaForType(Type type)
        {
            var schema = new OpenApiSchema();
#if OPENAPI_V2
            var properties = new Dictionary<string, IOpenApiSchema>();
#else
            var properties = new Dictionary<string, OpenApiSchema>();
#endif

            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var propName = prop.Name;
                if (_schemaGenerationOptions.NameResolver != null)
                    propName = _schemaGenerationOptions.NameResolver.GetPropertyName(prop);

                var propSchema = new OpenApiSchema();
                SetSchemaType(propSchema, prop.PropertyType);
                properties[propName] = propSchema;
            }

            schema.Properties = properties;
            return schema;
        }

        /// <summary>
        /// Sets basic type information on a schema from a CLR type.
        /// TODO: Add support for DateTime, DateTimeOffset, Guid, enum types, and collections.
        /// Currently these all fall through to "string" which may cause incorrect schema types.
        /// </summary>
        private static void SetSchemaType(OpenApiSchema schema, Type type)
        {
            var underlyingType = Nullable.GetUnderlyingType(type) ?? type;

#if OPENAPI_V2
            if (underlyingType == typeof(int) || underlyingType == typeof(long) || underlyingType == typeof(short) || underlyingType == typeof(byte))
                schema.Type = JsonSchemaType.Integer;
            else if (underlyingType == typeof(float) || underlyingType == typeof(double) || underlyingType == typeof(decimal))
                schema.Type = JsonSchemaType.Number;
            else if (underlyingType == typeof(string))
                schema.Type = JsonSchemaType.String;
            else if (underlyingType == typeof(bool))
                schema.Type = JsonSchemaType.Boolean;
            else
                schema.Type = JsonSchemaType.String;
#else
            if (underlyingType == typeof(int) || underlyingType == typeof(long) || underlyingType == typeof(short) || underlyingType == typeof(byte))
                schema.Type = "integer";
            else if (underlyingType == typeof(float) || underlyingType == typeof(double) || underlyingType == typeof(decimal))
                schema.Type = "number";
            else if (underlyingType == typeof(string))
                schema.Type = "string";
            else if (underlyingType == typeof(bool))
                schema.Type = "boolean";
            else
                schema.Type = "string";
#endif
        }

        /// <summary>
        /// Copies validation-related properties from source schema to target schema.
        /// </summary>
        private static void CopyValidationProperties(OpenApiSchema source, OpenApiSchema target)
        {
            if (source.MinLength != null) target.MinLength = source.MinLength;
            if (source.MaxLength != null) target.MaxLength = source.MaxLength;
            if (source.MinItems != null) target.MinItems = source.MinItems;
            if (source.MaxItems != null) target.MaxItems = source.MaxItems;
            if (source.Pattern != null) target.Pattern = source.Pattern;
            if (source.Minimum != null) target.Minimum = source.Minimum;
            if (source.Maximum != null) target.Maximum = source.Maximum;
            if (source.ExclusiveMinimum != null) target.ExclusiveMinimum = source.ExclusiveMinimum;
            if (source.ExclusiveMaximum != null) target.ExclusiveMaximum = source.ExclusiveMaximum;
            if (source.Format != null) target.Format = source.Format;
        }

        /// <summary>
        /// Resolves the container type for a parameter by inspecting [AsParameters] on method parameters.
        /// For nested paths (e.g., "Filter.MinAge"), walks the path to find the correct container type.
        /// </summary>
        private static Type? ResolveContainerType(string parameterName, MethodInfo? methodInfo)
        {
            if (methodInfo == null)
                return null;

            // Split dot-path into segments (e.g., "Filter.MinAge" => ["Filter", "MinAge"])
            var segments = parameterName.Split('.');

            foreach (var param in methodInfo.GetParameters())
            {
                if (param.GetCustomAttribute<AsParametersAttribute>() == null)
                    continue;

                var paramType = param.ParameterType;

                if (segments.Length == 1)
                {
                    // Simple case: direct property on [AsParameters] type
                    var property = paramType.GetProperties()
                        .FirstOrDefault(p => p.Name.Equals(segments[0], StringComparison.OrdinalIgnoreCase));
                    if (property != null)
                        return paramType;
                }
                else
                {
                    // Nested case: walk path segments to find the container of the leaf property.
                    // Note: ASP.NET Core minimal APIs do not currently emit dot-path parameters
                    // for nested [AsParameters] types. This branch is defensive code for potential
                    // future framework support or MVC controller scenarios.
                    // e.g., "Filter.MinAge" => find Filter on paramType, return Filter's type
                    var currentType = paramType;
                    for (int i = 0; i < segments.Length - 1; i++)
                    {
                        var navProp = currentType.GetProperties()
                            .FirstOrDefault(p => p.Name.Equals(segments[i], StringComparison.OrdinalIgnoreCase));
                        if (navProp == null)
                        {
                            currentType = null;
                            break;
                        }

                        currentType = navProp.PropertyType;
                    }

                    if (currentType != null)
                    {
                        var leafProp = currentType.GetProperties()
                            .FirstOrDefault(p => p.Name.Equals(segments[^1], StringComparison.OrdinalIgnoreCase));
                        if (leafProp != null)
                            return currentType;
                    }
                }
            }

            return null;
        }

        /// <summary>
        /// Finds the action parameter type that exposes <paramref name="firstSegment"/> as a property — the
        /// root container of a flattened nested [FromQuery] parameter. Unlike <see cref="ResolveContainerType"/>
        /// this does not require an [AsParameters] attribute (MVC [FromQuery] types are plain parameters).
        /// </summary>
        private static Type? ResolveRootType(string firstSegment, MethodInfo? methodInfo)
        {
            if (methodInfo == null)
                return null;

            foreach (var parameter in methodInfo.GetParameters())
            {
                if (parameter.ParameterType.GetProperty(firstSegment, BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase) != null)
                    return parameter.ParameterType;
            }

            return null;
        }

        /// <summary>
        /// Issue #211: checks that a flattened nested parameter's leaf type is actually validated — i.e. the
        /// SetValidator/ChildRules chain from the root validator reaches the leaf container. If the chain is
        /// broken (no SetValidator), the nested rules are not enforced at runtime and must not appear in the doc.
        /// </summary>
        private bool IsNestedValidationReachable(string parameterName, MethodInfo? methodInfo)
        {
            try
            {
                var segments = parameterName.Split('.');

                var rootType = ResolveRootType(segments[0], methodInfo);

                // Cannot resolve the root container — preserve prior behavior.
                if (rootType == null)
                    return true;

                var rootValidator = _validatorRegistry.GetValidator(rootType);

                // No validator for the bound type — runtime validates nothing along this path.
                if (rootValidator == null)
                    return false;

                var ancestorMembers = new string[segments.Length - 1];
                Array.Copy(segments, ancestorMembers, segments.Length - 1);

                return FluentValidationExtensions.IsNestedValidationWired(rootValidator, ancestorMembers, _schemaGenerationOptions);
            }
            catch (Exception e)
            {
                // A dynamic SetValidator(ctx => ...) factory may throw when probed with a fake context.
                // Such a member IS wired, so fall back to prior behavior (reachable).
                _logger.LogDebug(e, "Could not determine nested validation reachability for parameter '{ParameterName}'; assuming reachable.", parameterName);
                return true;
            }
        }

        /// <summary>
        /// Issue #209: a flattened nested parameter is required only when EVERY ancestor segment of the dot-path
        /// is itself required. Resolved from the action's root container type; leaf requiredness is handled by the caller.
        /// </summary>
        private bool IsParameterPathRequired(string parameterName, MethodInfo? methodInfo)
        {
            if (parameterName.IndexOf('.') < 0)
                return true;

            var segments = parameterName.Split('.');

            var currentType = ResolveRootType(segments[0], methodInfo);

            // If the root type cannot be determined, preserve the prior behavior (mark required).
            if (currentType == null)
                return true;

            for (int i = 0; i < segments.Length - 1; i++)
            {
                if (!IsPropertyRequiredInType(currentType, segments[i]))
                    return false;

                var propertyInfo = currentType.GetProperty(segments[i], BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase);
                if (propertyInfo == null)
                    return true; // path does not map to a real property — preserve prior behavior

                currentType = propertyInfo.PropertyType;
            }

            return true;
        }

        /// <summary>
        /// Checks whether <paramref name="propertyName"/> is required in <paramref name="containerType"/> by
        /// applying the container validator's FluentValidation rules (NotNull/NotEmpty) to a built schema.
        /// </summary>
        private bool IsPropertyRequiredInType(Type containerType, string propertyName)
        {
            var schema = BuildSchemaForType(containerType);

            if (schema.Properties == null || schema.Properties.Count == 0)
                return false;

            var resolvedName = OpenApiSchemaCompatibility.GetProperties(schema)
                .Select(property => property.Key)
                .FirstOrDefault(key => key.EqualsIgnoreAll(propertyName)) ?? propertyName;

            var validator = _validatorRegistry.GetValidator(containerType);
            if (validator == null)
                return false;

            var schemaProvider = new AspNetCoreSchemaProvider(null, _logger);
            var schemaContext = new AspNetCoreSchemaGenerationContext(
                schema: schema,
                schemaType: containerType,
                rules: _rules,
                schemaGenerationOptions: _schemaGenerationOptions,
                schemaProvider: schemaProvider);

            FluentValidationSchemaBuilder.ApplyRulesToSchema(
                schemaType: containerType,
                schemaPropertyNames: new[] { resolvedName },
                validator: validator,
                logger: _logger,
                schemaGenerationContext: schemaContext);

            return OpenApiSchemaCompatibility.RequiredContains(schema, resolvedName);
        }

        /// <summary>
        /// Extracts MethodInfo from an ApiDescription. For MVC controllers the action method lives on
        /// <see cref="Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor"/>; for minimal APIs
        /// it is exposed via EndpointMetadata.
        /// </summary>
        private static MethodInfo? GetMethodInfo(Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescription apiDescription)
        {
            if (apiDescription.ActionDescriptor is Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor controllerActionDescriptor)
                return controllerActionDescriptor.MethodInfo;

            return apiDescription.ActionDescriptor?.EndpointMetadata?
                .OfType<MethodInfo>()
                .FirstOrDefault();
        }
    }
}
