// Copyright (c) MicroElements. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using FluentValidation;
using MicroElements.OpenApi;
using MicroElements.OpenApi.Core;
using MicroElements.OpenApi.FluentValidation;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
#if !OPENAPI_V2
using Microsoft.OpenApi.Models;
#endif

namespace MicroElements.AspNetCore.OpenApi.FluentValidation
{
    /// <summary>
    /// <see cref="IOpenApiSchemaTransformer"/> that applies FluentValidation rules to OpenAPI schemas
    /// generated by Microsoft.AspNetCore.OpenApi.
    /// </summary>
    public class FluentValidationSchemaTransformer : IOpenApiSchemaTransformer
    {
        private readonly ILogger _logger;

        private readonly IValidatorRegistry _validatorRegistry;

        private readonly IReadOnlyList<IFluentValidationRule<OpenApiSchema>> _rules;
        private readonly SchemaGenerationOptions _schemaGenerationOptions;

        /// <summary>
        /// Initializes a new instance of the <see cref="FluentValidationSchemaTransformer"/> class.
        /// </summary>
        /// <param name="loggerFactory"><see cref="ILoggerFactory"/> for logging. Can be null.</param>
        /// <param name="validatorRegistry">Gets validators for a particular type.</param>
        /// <param name="fluentValidationRuleProvider">Rules provider.</param>
        /// <param name="rules">External FluentValidation rules. External rule overrides default rule with the same name.</param>
        /// <param name="schemaGenerationOptions">Schema generation options.</param>
        public FluentValidationSchemaTransformer(
            /* System services */
            ILoggerFactory? loggerFactory = null,

            /* MicroElements services */
            IValidatorRegistry? validatorRegistry = null,
            IFluentValidationRuleProvider<OpenApiSchema>? fluentValidationRuleProvider = null,
            IEnumerable<FluentValidationRule>? rules = null,
            IOptions<SchemaGenerationOptions>? schemaGenerationOptions = null)
        {
            // System services
            _logger = loggerFactory?.CreateLogger(typeof(FluentValidationSchemaTransformer)) ?? NullLogger.Instance;

            // FluentValidation services
            _validatorRegistry = validatorRegistry ?? throw new ArgumentNullException(nameof(validatorRegistry));

            // MicroElements services
            fluentValidationRuleProvider ??= new DefaultFluentValidationRuleProvider(schemaGenerationOptions);
            _rules = fluentValidationRuleProvider.GetRules().ToArray().OverrideRules(rules);
            _schemaGenerationOptions = schemaGenerationOptions?.Value ?? new SchemaGenerationOptions();

            _logger.LogDebug("FluentValidationSchemaTransformer Created");
        }

        /// <inheritdoc />
        public Task TransformAsync(
            OpenApiSchema schema,
            OpenApiSchemaTransformerContext context,
            CancellationToken cancellationToken)
        {
            var type = context.JsonTypeInfo.Type;

            // Skip primitive/simple types.
            if (type.IsPrimitiveType())
                return Task.CompletedTask;

            // Skip property-level schemas (we process only type-level schemas).
            // IOpenApiSchemaTransformer is called for each schema including property schemas.
            if (context.JsonPropertyInfo != null)
                return Task.CompletedTask;

            var typeContext = new TypeContext(type, _schemaGenerationOptions);

            var (validators, _) = Functional
                .Try(() => _validatorRegistry.GetValidators(type).ToArray())
                .OnError(e => _logger.LogWarning(0, e, "GetValidators for type '{ModelType}' failed", type));

            if (validators == null)
                return Task.CompletedTask;

            // Collect root schema and any embedded schemas from AllOf/OneOf/AnyOf.
            // This handles polymorphic/inheritance models where properties may be in sub-schemas.
            var allSchemas = new List<OpenApiSchema>();
            ProcessAllSchemas(schema, allSchemas);

            var schemaProvider = new AspNetCoreSchemaProvider(context);

            foreach (var validator in validators)
            {
                foreach (var currentSchema in allSchemas)
                {
                    var validatorContext = new ValidatorContext(typeContext, validator);
                    var schemaContext = new AspNetCoreSchemaGenerationContext(
                        schema: currentSchema,
                        schemaType: type,
                        rules: _rules,
                        schemaGenerationOptions: _schemaGenerationOptions,
                        schemaProvider: schemaProvider);

                    FluentValidationSchemaBuilder.ApplyRulesToSchema(
                        schemaType: type,
                        schemaPropertyNames: schemaContext.Properties,
                        validator: validator,
                        logger: _logger,
                        schemaGenerationContext: schemaContext);

                    try
                    {
                        FluentValidationSchemaBuilder.AddRulesFromIncludedValidators(
                            validatorContext: validatorContext,
                            logger: _logger,
                            schemaGenerationContext: schemaContext);
                    }
                    catch (Exception e)
                    {
                        _logger.LogWarning(0, e, "Applying IncludeRules for type '{ModelType}' failed", type);
                    }
                }
            }

            return Task.CompletedTask;
        }

        private static void ProcessAllSchemas(OpenApiSchema schema, List<OpenApiSchema> schemas)
        {
            schemas.Add(schema);

            var collectionsOfSchemas = new IEnumerable<OpenApiSchema>[]
            {
                OpenApiSchemaCompatibility.GetAllOf(schema),
                OpenApiSchemaCompatibility.GetOneOf(schema),
                OpenApiSchemaCompatibility.GetAnyOf(schema),
            };

            foreach (var collectionOfSchemas in collectionsOfSchemas)
            {
                foreach (var embeddedSchema in collectionOfSchemas)
                {
                    if (embeddedSchema.Properties == null || embeddedSchema.Properties.Count == 0)
                    {
                        continue;
                    }

                    schemas.Add(embeddedSchema);
                }
            }
        }
    }
}
